### ISSUE TITLE
Limit the content from scrolling behind the header

### ISSUE THREAD

**Issue by rox163** [ciena-frost/ember-frost-modal-input#24]
Limit how much content is visible behind the header. Right now the content visually clashes with the header elements as it scrolls behind. Limit the scroll to only go about 55px into [behind] the header.

**Comment by sglanzer** [comment]
I'd say 10px behind the header and footer should be sufficient

**Comment by job13er** [comment]
May want to run that by UX (if you haven't already) the original ask was for it to go all the way behind the header/footer.

**Comment by sglanzer** [comment]
I'll confirm it with UX

**Comment by sglanzer** [comment]
Discussed with Brian - we're keeping the 0.95 opacity footer as-is, but the header is moving to be opaque

**Comment by rox163** [comment]
Fixed in #23
