### ISSUE TITLE
Don't always add 'frost-modal-input' class

### ISSUE THREAD

**Issue by job13er** [ciena-frost/ember-frost-modal-input#29]
It appears we are always adding the `frost-modal-input` class to all instances of `.ember-remodal.window`, even if those elements have nothing to do with the `frost-modal-input` instance (for example, if they were created by a `frost-modal-dialog` instance). 

https://github.com/ciena-frost/ember-frost-modal-input/blob/master/addon/components/frost-modal-input.js#L159
```js
didRender () {
  Ember.$('.ember-remodal.window').addClass('frost-modal-input')
 },
```

Let's stop doing that. At the very least, we can specifically exclude those items that already have `frost-modal-dialog` class, but a more robust solution would probably be preferred.

**Comment by rox163** [comment]
resolved in v 5.0.0
